apiVersion: v1
kind: Service
metadata:
  name: httpservertest
  namespace: default
spec:
  ports:
    - name: 80tcp1-httpservertest
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: httpservertest
  type: ClusterIP

